# Generated by Django 2.0.4 on 2018-07-22 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_promotion_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='thumbnail',
            new_name='image',
        ),
    ]
