# Generated by Django 2.0.4 on 2018-07-22 21:02

from django.db import migrations, models
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_auto_20180722_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, help_text='Enter a comma-separated tag string', null=None, to='promotions.Tagulous_Promotion_tags'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
