# Generated by Django 2.0.4 on 2018-07-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0005_auto_20180722_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='casino',
            name='state',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
