# Generated by Django 2.0.4 on 2018-07-31 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0006_auto_20180722_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='bingo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casino',
            name='keno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casino',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='casino',
            name='lon',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='casino',
            name='num_hotel_rooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='casino',
            name='num_slots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='casino',
            name='num_table_games',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='casino',
            name='poker',
            field=models.BooleanField(default=False),
        ),
    ]
