# Generated by Django 2.0.4 on 2018-08-12 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0008_auto_20180812_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='image',
        ),
        migrations.AddField(
            model_name='promotion',
            name='image_file',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
