# Generated by Django 2.0.4 on 2018-08-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0009_auto_20180812_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='casino_logos'),
        ),
        migrations.AddField(
            model_name='casino',
            name='zip_code',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
