# Generated by Django 2.0.4 on 2018-08-13 02:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0010_auto_20180813_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
